parameters:
  eye_on_hand: false
  freehand_robot_movement: true
  move_group: manipulator
  move_group_namespace: /
  namespace: /sawyer_eye_on_base/
  robot_base_frame: reference/base
  robot_effector_frame: reference/right_l6
  tracking_base_frame: rgb_camera_link
  tracking_marker_frame: camera_marker
transformation:
  qw: 0.403103741465
  qx: -0.536645781657
  qy: -0.629341075233
  qz: 0.391725017928
  x: 0.448928440159
  y: -0.487110390005
  z: 0.546397869294
