server_host: "http://10.184.17.177"
server_port: 8000
username: "sunhaowen"
password: "sunhaowen"
wait_time: 60
image_path: "/home/haowensun/robot/shw_robot_grasp/src/Robot_Grasp/scripts/tmp/image/"
detector_name: "VMRN"